# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tildwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(302, 172)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        Form.setFont(font)
        Form.setStyleSheet("border: none;")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 301, 171))
        self.frame.setStyleSheet("background-color: rgb(16, 16, 36);\n"
"border: none;\n"
"border-radius:0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(0, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgb(192, 187, 255);\n"
"border-radius:2px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 60, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgb(192, 187, 255);\n"
"border-radius:2px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 100, 281, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:rgb(192, 187, 255);\n"
"border-radius:2px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 140, 51, 31))
        self.pushButton.setStyleSheet("background-color: rgb(206, 206, 216);\n"
"border-radius:0px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 140, 51, 31))
        self.pushButton_2.setStyleSheet("background-color:  rgb(206, 206, 216);\n"
"border-radius:0px;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.titlebar = QtWidgets.QFrame(self.frame)
        self.titlebar.setGeometry(QtCore.QRect(0, 0, 301, 21))
        self.titlebar.setStyleSheet("background-color: rgb(36, 36, 56);")
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.closebtn = QtWidgets.QPushButton(self.titlebar)
        self.closebtn.setGeometry(QtCore.QRect(280, 0, 21, 21))
        self.closebtn.setMinimumSize(QtCore.QSize(1, 1))
        self.closebtn.setMaximumSize(QtCore.QSize(31, 31))
        self.closebtn.setStyleSheet("background-color: rgb(255, 98, 98);\n"
"color:  rgb(255, 98, 98);\n"
"border-radius:0px;")
        self.closebtn.setText("")
        self.closebtn.setObjectName("closebtn")
        self.titlebar.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Account entrance"))
        self.lineEdit.setText(_translate("Form", "login"))
        self.lineEdit_2.setText(_translate("Form", "password"))
        self.lineEdit_3.setText(_translate("Form", "phone number"))
        self.pushButton.setText(_translate("Form", "Log in"))
        self.pushButton_2.setText(_translate("Form", "Sign up"))
        self.closebtn.setToolTip(_translate("Form", "Close"))
